### ISSUE TITLE
Add options to choose colour and/or shape of point in scatterplot

### ISSUE THREAD

**Issue by FrancescoVit** [biobakery/Maaslin2#3]
Dear Maaslin2 developers,

using the function, everything looks fine and nice. Very useful indeed, Thanks!

I'm using far less data than the one used in your example data sets, and I would find extremely useful to add parameters to (optionally) map one of the variables in metadata to points colour or shape in scatterplots. It could help to better interpret the microbes/continuous data relation
Maybe also the possibility to plot label could be useful.

Best,
Francesco.

**Comment by himelmallick** [comment]
@FrancescoVit Thanks for the suggestion. 

@grahnavard Could you please take note of this future enhancement? It seems like a good extension to the visualization script.

**Comment by fconstancias** [comment]
Dear Maaslin2 users, developpers,

Actually the ability to store a list of ggplot objects as a return of the fuction would be great so we could customize the plots in R.

Best

**Comment by FrancescoVit** [comment]
Any chances or plans to see this feature implemented? 
Francesco.
